name: Collect AQI Data Hourly

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  collect_aqi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install hopsworks pandas

      - name: Create data folder
        run: mkdir -p data

      - name: Set up environment variables
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Set Hopsworks API key
        run: echo "HOPSWORKS_API_KEY=${{ secrets.HOPSWORKS_API_KEY }}" >> $GITHUB_ENV

      - name: Download aqi_data.csv from Hopsworks
        run: python data_collection/main.py preload

      - name: Run AQI data collection and append new data
        run: python data_collection/main.py collect

      - name: Upload database artifact
        uses: actions/upload-artifact@v4
        with:
          name: aqi_database
          path: data/aqi_data.db
