name: Data Collect AQI

on:
  schedule:
    - cron: '0 5 * * *'  # Run daily at 5 AM UTC
  workflow_dispatch:

jobs:
  collect-aqi:
    runs-on: ubuntu-latest
    env:
      HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      HOPSWORKS_PROJECT: ${{ secrets.HOPSWORKS_PROJECT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AQI data collection script
        run: python pipeline/data_collect_aqi.py
