name: AQI Model Training Pipeline

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 0 1,15 * *' # Runs at midnight UTC on the 1st and 15th of every month

jobs:
  run-training-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          HOPSWORKS_PROJECT: ${{ secrets.HOPSWORKS_PROJECT }}
        run: |
          python pipeline/model_training_pipeline.py